### ISSUE TITLE
JavaScript scrolling issues

### ISSUE THREAD

**Issue by Heydon** [bbc/gef-docs#56]
I believe we have a JavaScript-powered smooth scrolling thing? It seems to be interfering with some reference implementation behaviour. We can use CSS instead:

```css
body {
  scroll-behavior: smooth;
}
```

(The **Info panel** is having scrolling issues in Chrome. Not happening when I isolate the reference implementation in CodePen, or use Firefox or Safari.)
